# Generated by Django 4.2.7 on 2023-11-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='cata_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.postcatagory'),
            preserve_default=False,
        ),
    ]
